scorpio_base:
  ros__parameters:
    base_frame_id: "base_footprint"
    odom_frame_id: "odom"
    stm32_port: "/dev/ttyS0"
    motor_port: "/dev/ttyS3"
    stm32_baud: 115200
    motor_baud: 57600
    publish_odometry: true
    odom_topic: "base/odometry"
    send_transform: false
    limited_speed: 1.0
    wheelbase: 0.315
    use_stamped_vel: True
